language: node_js
sudo: false
node_js:
  - 6.4

before_install:
  - npm i nsp -g
  - npm install -g generator-github-create

after_script:
  - nsp audit-package
  - npm run coverage

notifications:
  webhooks:
    urls:
      secure: "SNXwOj0fcwzJf5nkJbPiy1o03VwRMhAl6cZh+kbpzb/Av9p9zLuBxWP5ctZnLnZje/DJCydoYMKH4OkPeHzajUrPLKLhO+QX4wMjBKhrdoJQhcYznHEkK3aGW7bUmQT30twP6UWRgVbn+xRw6VAwA2DIvRaqp5CGcLt9qNE/z43NUaYihvkKuK1aXTEqGC/qkS/2TNgvuM0TcsQ0ybkuOq+Ed60+Zz3oY9q1YTRZAa7kUONeo8CGIsnX6IfIyZC2/apVoeNqLaFMkUSp5RLQhod+hUByTfiZ6Caqx4gJbMXGtdiDoOXzv0COLSGxmyMYihHtzwtF91yM4ZwhZ7IuiZXgPvqgZnrU+vWsGzn/PrqbXscOHl9ir3Oo0DtnJgAKjtubD9Jcf/ZCvY373z9LRCwfcVUOqzbRo2z6LGrmXfrUXtnjgvkermo4GzgDdeQ1Cft1sZMsbVBrLFbTThWyJguywPt++Ti5oxl3rIQT6dsuE5mrLIwSxalwV/7lz25cykieRIDqRlBiyR+wN5vtZnWzZ/cuIJdPmihrdlU5CAcQ7e6Q1bT8s9vXDznrjd8BK9sen+uk/S1sREmKvrkc182C6LAk+OY8n9kqdEMA7yz7Pj4kWSigu4gBYl963W6QZeefcDLq0jkV5Ct1v42l+SjweXk40v6+KITHJlz2Bk0="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
